name             'scala-jenkins-infra'
maintainer       'Typesafe, Inc.'
maintainer_email 'adriaan@typesafe.com'
license          'All rights reserved'
description      'Installs/Configures the Scala Jenkins infrastructure'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.0'

depends 'windows'
depends 'aws'
depends 'java'
depends 'git'
depends 'chef-sbt'
depends 'wix', '~> 1.0.2'
depends 'jenkins'