# TODO: this kind of works, but the cookbook won't run in virtual box:
#  - chef-solo can't access the vault on the chef server (passwords etc)
# vagrant box add utopic-daily https://cloud-images.ubuntu.com/vagrant/utopic/current/utopic-server-cloudimg-amd64-vagrant-disk1.box
# vagrant init utopic-daily
# vagrant up
# centos: vagrant box add chef/centos-7.0
Vagrant.configure("2") do |config|
  config.vm.define "default" do |master|
    master.vm.box = "utopic-daily"
    master.vm.provision :chef_zero do |chef|
      chef.cookbooks_path = "~/git/cookbooks"
      # after a long struggle tring to get chef-zero/solo to work with chef-vault, dumped the databags in plain text from admin account using:
      # for item in $(knife data bag show master); do knife vault show --format json master $item  > .chef/data_bags/master/$item.json; done
      chef.data_bags_path = "data_bags"
      chef.node_name = "jenkins-master"
      # TODO: chef.encrypted_data_bag_secret_key_path
      chef.add_recipe("scala-jenkins-infra::master-init")
      chef.add_recipe("scala-jenkins-infra::master-config")
      chef.add_recipe("scala-jenkins-infra::master-jenkins") # do not run on first provision -- must run up to master-config and allow jenkins to restart
    end
    master.vm.network "public_network"
    master.vm.provider "virtualbox" do |v|
      v.memory = 4096
      v.cpus = 2
    end
  end


  config.vm.define "worker" do |worker|
    worker.vm.box = "utopic-daily"
    worker.vm.provision :chef_zero do |chef|
      chef.cookbooks_path = "~/git/cookbooks"
      # after a long struggle tring to get chef-zero/solo to work with chef-vault, dumped the databags in plain text from admin account using:
      # for item in $(knife data bag show master); do knife vault show --format json master $item  > .chef/data_bags/master/$item.json; done
      chef.data_bags_path = "data_bags"
      chef.node_name = "jenkins-worker-vagrant"
      # TODO: chef.encrypted_data_bag_secret_key_path
      chef.add_recipe("scala-jenkins-infra::worker-init")
      chef.add_recipe("scala-jenkins-infra::worker-config")
    end
    worker.vm.network "public_network"
    # worker.vm.provider "virtualbox" do |v|
    #   v.memory = 4096
    #   v.cpus = 2
    # end
  end
end
